config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :homes, only: [:top, :about]
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

    validates :name, presence: true, uniqueness:true, length:{in:2..20}
    validates :introduction, length:{ maximum: 50}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    @user = current_user.id
    user_path(@user)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remenber_me]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_correct_user,only: [:edit]

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end


  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully"
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully"
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_correct_user,only: [:edit]

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end


  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice:"You have updated user successfully."
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
<div class="col-md-3">
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
    <table class="table">
        <tbody>
            <tr>
                <th>name</th>
                <th><%= user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
            </tr>
        </tbody>
    </table>
    <p>
        <%= link_to edit_user_path(user) do %>
        <button type="button" class="btn btn-outline-secondary btn-sm btn-block"><i class="fas fa-user-cog"></i></button>
        <% end %>
    </p>
    <%= form_with model:book, url: books_path, method: :post, local:true do |f| %>
    <h2 class="mt-3">New book</h2>
    <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title %>
    </div>
    <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_field :body %>
    </div>
    <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
        <% end %>
</div>

app/views/books/edit.html.erb
<main>
  <p id="notice">
    <%= notice %>
  </p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <div id="error_explanation">
          <% if @book.errors.any? %>
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved: </h3>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
        </div>
        <h1>Editing Book</h1>
        <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_area :title %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_field :body %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
          <% end %>
        </div>
        <%= link_to "Show", book_path(@book) %>
         |
        <a href="/books">Back</a>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
    <p id="notice"></p>
    <div class="container px-5 px-sm-0">
        <div id="error_explanation">
            <% if @book.errors.any? %>
                <h3><%= @book.errors.count %> errors prohibited this obj from being saved: </h3>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
        </div>
        <div class="row">
            <%= render "books/sidebar", book: @book, user: @user %>
            <div class="col-md-8 offset-md-1">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @books.each do |book| %>
                        <tr>
                            <td><%= link_to user_path(book.user_id) do %>
                            <%= attachment_image_tag book.user, :profile_image,  format:"jpeg", fallback: "no_image.jpg", size: "40x40" %>
                            <% end %>
                            </td>
                            <td><%= link_to book.title, book_path(book) %></td>
                            <td><%= book.body %></td>
                        </tr>
                        <% end %>
                </table>
            </div>
        </div>
    </div>
</main>

app/views/books/show.html.erb
<main>
<p id="notice">
  <%= notice %>
</p>
  <div class="container">
    <div class="row">
      <%= render "books/sidebar", book: @book, user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
                <%= link_to @user.name, user_path(@user.id) %>
                </td>
              <td>
                <%= link_to @book.title, book_path(@book) %>
                </td>
              <td><%= @book.body %></td>
              <%if @user == current_user %>
              <td><%=link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path, method: :delete, class: "btn btn-sm btn-danger" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/_devise_messages.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/homes/about.html.erb
<main>
  <p id ="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <%= render "homes/devise_messages" %>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in" >Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                  <%= link_to "Home", user_path(current_user), class:"fas fa-home nav-link text-light" %>
              </li>
              <li>
                <a class="fas fa-users nav-link text-light" href="/users">Users</a>
              </li>
              <li>
                <a class="fas fa-book-open nav-link text-light" href="/books">Books</a>
              </li>
              <li>
                  <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
              </li>
            <% else %>
              <li>
                <a class="fas fa-home nav-link text-light" href="/">Home</a>
              </li>
              <li>
                <a class="fas fa-link nav-link text-light" href="/home/about">About</a>
              </li>
              <li>
                <a class="fas fa-user-plus nav-link text-light" href="/users/sign_up">sign up</a>
              </li>
              <li>
                <a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in">login</a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <%= yield %>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
          <div id="error_explanation">
            <% if @user.errors.any? %>
              <h3><%= @user.errors.count %> errors prohibited this obj from being saved: </h3>
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              <% end %>
          </div>
        <%= form_with model:@user, local: true  do |f| %>
          <h3>Name</h3>
          <%= f.text_field :name %>
          <h3>Image</h3>
          <%= f.attachment_field :profile_image %>
          <h3>Introduction</h3>
          <%= f.text_area :introduction %>
          <%= f.submit "Update User" %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render "books/sidebar", book: @book, user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image,  format:"jpeg", fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>

            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
    <p id="notice">
        <%= notice %>
    </p>
    <div class="container px-5 px-sm-0">
    <div class="row">
        <%= render "books/sidebar", book: @book, user: @user %>
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @books.each do |book| %>
                    <tr>
                        <td><%= link_to user_path(book.user_id) do %>
                            <%= attachment_image_tag book.user, :profile_image,  format:"jpeg", fallback: "no_image.jpg", size: "40x40" %>
                            <% end %></td>
                        <td><%= link_to book.title, book_path(book) %></td>
                        <td><%= book.body %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    </div>
</main>